pep_version: 2.0.0
sample_table: "simulated_test.csv"
sample_modifiers:
    derive:
        attributes: [file_path]
        sources:
            source1: "test/"
            source2: "results/test/input_fastqs/"
